[package]
name        = "llama-desktop"
version     = "1.0.0"
authors     = ["Montegasppα Cacilhας <montegasppa@cacilhas.info>"]
license     = "BSD-3-Clause"
readme      = "README.md"
homepage    = "https://crates.io/crates/llama-desktop"
repository  = "https://github.com/cacilhas/llama-desktop"
keywords    = ["desktop", "artificial intelligence", "ai model"]
description = "Desktop interface for Ollama"
edition     = "2021"
build       = "build.rs"

[profile.release]
opt-level = "s"
debug = false
rpath = false
strip = true

[dependencies]
eyre = "0.6"
serde_json = "1.0"
slint = "1.3"
tokio-stream = "0.1"
url = "2.5"

[dependencies.reqwest]
versoin = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
vesion = "1.35"
features = ["full"]

[build-dependencies]
slint-build = "1.3"
