[package]
name = "llama-desktop"
version = "0.1.0"
authors = ["Montegasppα Cacilhας <montegasppa@cacilhas.info>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
slint = "1.3"
tokio-stream = "0.1"
url = "2.5"

[dependencies.ollama-rs]
version = "0.1"
features = ["stream"]

[dependencies.tokio]
vesion = "1.35"
features = ["full"]

[build-dependencies]
slint-build = "1.3"
