import { Button, ComboBox, ScrollView, Spinner, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
  title: "Llama Desktop";
  min-width: 300px;
  max-width: 600px;
  min-height: 400px;
  max-height: 1080px;
  background: #100408;
  padding: 5px;
  default-font-family: "Bellota";
  forward-focus: prompt;

  in-out property <[string]> ai-models: [];
  in-out property <string> current-model: "Loading...";
  callback query(string);

  function send-prompt() {
    if (!spinner.visible) {
      response.text = "";
      spinner.visible = true;
      query(prompt.text);
    }
  }

  public function update-response(res: string) {
    response.text += res;
  }

  public function response-done() {
    spinner.visible = false;
  }

  VerticalLayout {
    width: parent.width - 10px;
    height: parent.height - 10px;

    // 1st row
    HorizontalLayout {
      width: parent.width;
      height: 28px;
      alignment: stretch;

      Image {
        source: @image-url("./icon.png");
      }

      // Filler
      Rectangle {
        width: 38px;
        height: parent.height;
      }

      Text {
        color: #541021;
        font-family: "Aclonica";
        font-size: 24px;
        font-weight: 900;
        text: "Model:";
      }

      ComboBox {
        current-value: root.current-model;
        model: root.ai-models;
        selected(value) => { root.current-model = value; }
      }
    }

    // Filler
    Rectangle {
      width: parent.width;
      height: 5px;
    }

    // 2nd row
    prompt := TextEdit {
      width: parent.width;
      height: (parent.height - 66px) / 2;
      font-size: 18px;
      text: "Why is the sky blue?";
      wrap: word-wrap;
    }

    // Filler
    Rectangle {
      width: parent.width;
      height: 5px;
    }

    // 3rd row
    Button {
      x: 5px;
      width: parent.width - 10px;
      height: 24px;
      primary: true;
      text: "Send";
      clicked => { send-prompt(); }
    }

    // Filler
    Rectangle {
      width: parent.width;
      height: 5px;
    }

    // 4nd row
    Rectangle {
      width: parent.width;
      height: (parent.height - 66px) / 2;

      response := TextEdit {
        width: parent.width;
        height: parent.height;
        font-size: 18px;
        read-only: true;
        wrap: word-wrap;
      }

      spinner := Spinner {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        indeterminate: true;
        visible: false;
      }
    }
  }
}
